name: Trivy Scan

on:
  push:
    branches:
      - main

jobs:
  security_scan:
    name: Security Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t python-trivy-test:latest .

      - name: Scan Docker image with Trivy and upload results to Code Scanning
        uses: aquasecurity/trivy-action@v0
        with:
          image-ref: python-trivy-test:latest
