name: Trivy Scan

on:
  push:
    branches:
      - main  # Adjust this to the branch you want to trigger the workflow o

jobs:
  security_scan:
    name: Security Scan
    runs-on: ubuntu-latest  # You can change the runner to other environments if needed

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image  # Modify this step to build your Docker image
        run: docker build -t python-trivy-test:latest .
        
      - name: Image Scan
        uses: aquasecurity/trivy-action@master
        with:
           image-ref: python-trivy-test:latest
           #security-checks: 'vuln,secret,config'
           format: 'sarif'
           severity: 'CRITICAL,HIGH'
           ignore-unfixed: true
           vuln-type: 'os,library'
           output: 'trivy-results.sarif'
           
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        if: always()
        with:
          sarif_file: 'trivy-results.sarif'
          token: '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'


