name: Trivy Scan

on:
  push:
    branches:
      - main  # Adjust this to the branch you want to trigger the workflow on

jobs:
  security_scan:
    name: Security Scan
    runs-on: ubuntu-latest  # You can change the runner to other environments if needed

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Trivy
        run: |
          #wget wget https://github.com/aquasecurity/trivy/releases/latest/download/trivy
          #chmod +x trivy
          #sudo mv trivy /usr/local/bin/
          sudo apt update
          sudo apt install snapd
          sudo snap install trivy

      - name: Build Docker image  # Modify this step to build your Docker image
        run: docker build -t python-trivy-test:latest .

      - name: Scan Docker image with Trivy
        run: |
          trivy image python-trivy-test:latest

